feat: Add Parquet format to data page
openfoodfacts/openfoodfacts-web pull request #629
Opened 2024-10-28 08:41 UTC by jeremyarancio

### What
- We recently converted the JSONL dump into the Parquet format, which is more suitable for analytic queries and lightweight.
- The dataset is hosted on the [Hugging Face platform](https://huggingface.co/datasets/openfoodfacts/product-database/tree/main).
- This commit adds a section to the data webpage to allow the database users to load the Parquet file.

### Part of 
- [PR](https://github.com/openfoodfacts/robotoff/pull/1436): Add CLI command to convert and push JSONL to Huggingface

2024-10-29 10:49 UTC, teolemon commented on lang/aa/texts/data.html
> +<p>A cleaner version of the JSONL dump is also available in the <a href="https://parquet.apache.org/">Parquet format</a>. This data format is optimized for columnar queries, which is particular conve
```suggestion
<p>A simplified of the JSONL dump is also available in the <a href="https://parquet.apache.org/">Parquet format</a>. This data format is optimized for column-oriented queries, which is particular convenient for data analysis. i.e. you can select just the columns you care about, reducing the size of the file you have to handle. You don't have to download all columns, simplifying your data-processing on entry-level computers.</p>
```

2024-11-03 09:12 UTC, jeremyarancio commented
@teolemon 
I integrated your feedback.
Let me know if it's good

2024-11-05 09:33 UTC, teolemon requested changes
@jeremyarancio you're editing the aa page, you should edit the en/texts/data.html page

2024-11-05 12:43 UTC, jeremyarancio commented
> @jeremyarancio you're editing the aa page, you should edit the en/texts/data.html page

Indeed! It's fixed

2024-11-05 13:46 UTC, hangy commented on lang/en/texts/data.html
> +<p>A simplified version of the JSONL dump is also available in the <a href="https://parquet.apache.org/">Parquet format</a>. During the conversion, we filtered columns that contains duplicated inform
I think the `<p>` tag is never closed. The other paragraphs probably also need `<p>` tags, as this is pure HTML without Markdown processing

2024-11-05 14:18 UTC, jeremyarancio commented on lang/en/texts/data.html
> +<p>A simplified version of the JSONL dump is also available in the <a href="https://parquet.apache.org/">Parquet format</a>. During the conversion, we filtered columns that contains duplicated inform
You're right!
Should be ok now

2024-11-14 13:54 UTC, jeremyarancio commented
@teolemon 
Is the PR good for merge?

2024-11-16 13:36 UTC, teolemon commented on lang/en/texts/data.html
> +<li>Data are organized by column, rather than by row, which saves storage space and speeds up analytics queries, i.e. you can select just the columns you care about, optimizing query performances, ev
```suggestion
<li>Data is organized by column, rather than by row, which saves storage space and speeds up analytics queries, i.e. you can select just the columns you care about, optimizing query performances, even on entry-level computers.</li>
```

2024-11-16 13:36 UTC, teolemon commented on lang/en/texts/data.html
> +<li>Highly efficient data compression and decompression, making it good for storing and sharing big data of any kind,</li>
```suggestion
<li>Highly efficient data compression and decompression, making it good for storing and sharing big datasets of any kind,</li>
```

2024-11-17 14:04 UTC, teolemon approved these changes
LGTM @jeremyarancio 👌 you can merge, and it will be deployed to .net within minutes.

2024-11-20 14:04 UTC, merged